<?php $this->load("include/html_head"); ?>
<div id="body">
		<div class="header">
    	<span class="welcome left">
        	Welcome Back <?php echo $this->user; ?>
        </span>
        <span class="menu right">
        	<a href="/index/index" target="_blank">Show Site</a> | 
            <a href="/admin/logout">Logout</a>
        </span>
        <div class="clear"></div>
    </div>
    <div class="tabs">
        <div class="tab active" id="tab_home">
            <img src="/image/admin/Profile.png" alt="Home" title="Home" /><br />
            Home
        </div>
        <?php 
			foreach($this->tabs as $key => $tab){
			?>
        <div class="tab" id="tab_<?php echo strtolower($tab['name']); ?>">
            <img src="<?php echo $tab['image'] ?>" alt="<?php echo $tab['name']; ?>" title="<?php echo $tab['name']; ?>" /><br />
            <?php echo $tab['name']; ?>
        </div>
            <?php
			}
		?>
        <div class="clear">&nbsp;</div>
    </div>
    <div class="content">
    	<div class="submenu">
        </div>
        <div class="addon_content">
        </div>
        <div class="clear"></div>
        <div class="footer">
            <center>&copy; Lightweight CMS 2011-2013</center>
        </div>
        <div class="overlay" style="display:none">
        	<div class="loading">
            	Please Wait<br />
                The Server is taking some time<br />
                <img src="/image/admin/Loading.gif" alt="Loading" title="Loading" />
            </div>
        </div>
    </div>
</div>
<?php $this->load("include/html_foot"); ?>