<p>Welcome to Lightweight CMS<br>
  In this content Management System you can edit the content shown on your site's  also able to manage the plugins used on your site.</p>
<p>The Plugins allows you to install new Plugins and Manage exsiting meaning you have toltal control over your site all pluigns are operated Indervidualy however they have access to your database as such dont install any Plugin that is not trusted!</p>
<p>Inside the Content System will show a list of all Content Pages you cuurrently have and allows you to manage these by Adding a new page, Removing an Old Page or Editing an page currently shown on your website.
</p>
