<?php 
	echo $this->menu->buildOutput();
?>
These are your currently installed plugins some are system plugins and can't be deleted.
<ul class="table">
	<li>
    	<ul class="header">
        	<li class="id">ID</li>
        	<li class="name">Plugin Name</li>
        	<li class="author">Author</li>
        	<li class="version">Version</li>
        	<li class="info">Info</li>
        	<li class="delete">Delete</li>
        	<li class="active">Active</li>
            <li class="clear"></li>
        </ul>
    </li>
<?php
	foreach($this->data as $key => $val){
?>
	<li>
    	<ul class="row">
        	<li class="id"><?php echo $val['plugin_id']; ?></li>
        	<li class="name">
            		<a href="/admin/plugin/<?php echo strtolower($val['name']); ?>/index"><?php echo $val['name']; ?></a>
            </li>
        	<li class="author"><?php echo $val['author']; ?></li>
        	<li class="version"><?php echo $val['version']; ?></li>
            <li class="info">
            <?php
				if($val['visible'] == 1){
            ?>
            	<a href="<?php echo $this->url->getMethodAddr("info")."/id/".$val['plugin_id'] ?>">Edit</a>
            <?php
				}else{
			?>
            	<a href="<?php echo $this->url->getMethodAddr("info")."/id/".$val['plugin_id'] ?>">Show</a>
            <?php
				}
            ?>
            </li>
        	<li class="delete">
            <?php
				if($val['visible'] == 1){
            ?>
				<a href="<?php echo $this->url->getMethodAddr("delete")."/id/".$val['plugin_id'] ?>">Delete</a>
			<?php
				}else{
					echo "&nbsp";
				}
            ?>
            </li>
            <li class="active">
            	<?php
				if($val['visible'] == 1){
					if($val['active'] == '1'){
						?>
					<a href="<?php echo $this->url->getMethodAddr("disable")."/id/".$val['plugin_id'] ?>">
                    <img height="20" src="<?php echo $this->url->getCMSImage("Tick") ?>" alt="Disable" title="Disable" />
                    </a>
					<?php
                    }else{
					?>
					<a href="<?php echo $this->url->getMethodAddr("enable")."/id/".$val['plugin_id'] ?>">
					<img height="20" src="<?php echo $this->url->getCMSImage("Cross") ?>" alt="Enable" title="Enable" />
					</a>
                    <?php
					}
				}else{
					?>
                    <img height="20" src="<?php echo $this->url->getCMSImage("Tick") ?>"/>
                    <?php
				}
				?>
            </li>
            <li class="clear"></li>
        </ul>
    </li>
	<div class="cear"></div>
<?php
	}
?>
</ul>
<div class="cear"></div>