<?php 
	echo $this->menu->buildOutput();
?>
<style type="text/css">
ul, li{
	list-style:none;
	margin-left:0;
	padding:0;
}
ul li ul li{
	float:left;
	height:25px;
	line-height:25px;
	overflow-y:hidden;
}

ul li ul.row:hover li{
	background-color:#2DE6ED;
}

ul.table{
	width:800px;
}

ul.table li.id{
	width:60px;
	text-align:center;
}

ul.table li.name{
	width:300px;
}

ul.table li.author{
	width:160px;
}

ul.table li.version{
	width:80px;
}

ul.table li.info{
	width:60px;
	text-align:center;
}

ul.table li.active{
	width:70px;
	height:22px;
	text-align:center;
	padding-top:3px;
}

ul.table ul.header li.active{
	padding-top:0;
	height:30px;
}

ul.table li.delete{
	width:70px;
	text-align:center;
}

ul.table ul.header{
	background-color:#888;
	height:20px;
	border-top-left-radius: 10px;
	border-top-right-radius: 10px;
}

.clear{
	clear:both;
}
</style>
These are your currently installed plugins some are system plugins and can't be deleted.
<ul class="table">
	<li>
    	<ul class="header">
        	<li class="id">ID</li>
        	<li class="name">Plugin Name</li>
        	<li class="author">Author</li>
        	<li class="version">Version</li>
        	<li class="info">Info</li>
        	<li class="delete">Delete</li>
        	<li class="active">Active</li>
            <li class="clear"></li>
        </ul>
    </li>
<?php
	foreach($this->data as $key => $val){
?>
	<li>
    	<ul class="row">
        	<li class="id"><?php echo $val['plugin_id']; ?></li>
        	<li class="name">
            		<a href="/admin/plugin/<?php echo strtolower($val['name']); ?>/index"><?php echo $val['name']; ?></a>
            </li>
        	<li class="author"><?php echo $val['author']; ?></li>
        	<li class="version"><?php echo $val['version']; ?></li>
            <li class="info">
            <?php
				if($val['visible'] == 1){
            ?>
            	<a href="<?php echo $this->url->getMethodAddr("info")."/id/".$val['plugin_id'] ?>">Edit</a>
            <?php
				}else{
			?>
            	<a href="<?php echo $this->url->getMethodAddr("info")."/id/".$val['plugin_id'] ?>">Show</a>
            <?php
				}
            ?>
            </li>
        	<li class="delete">
            <?php
				if($val['visible'] == 1){
            ?>
				<a href="<?php echo $this->url->getMethodAddr("delete")."/id/".$val['plugin_id'] ?>">Delete</a>
			<?php
				}else{
					echo "&nbsp";
				}
            ?>
            </li>
            <li class="active">
            	<?php
				if($val['visible'] == 1){
					if($val['active'] == '1'){
						?>
					<a href="<?php echo $this->url->getMethodAddr("disable")."/id/".$val['plugin_id'] ?>">
                    <img height="20" src="<?php echo $this->url->getCMSImage("Tick") ?>" alt="Disable" title="Disable" />
                    </a>
					<?php
                    }else{
					?>
					<a href="<?php echo $this->url->getMethodAddr("enable")."/id/".$val['plugin_id'] ?>">
					<img height="20" src="<?php echo $this->url->getCMSImage("Cross") ?>" alt="Enable" title="Enable" />
					</a>
                    <?php
					}
				}else{
					?>
                    <img height="20" src="<?php echo $this->url->getCMSImage("Tick") ?>"/>
                    <?php
				}
				?>
            </li>
            <li class="clear"></li>
        </ul>
    </li>
<?php
	}
?>
</ul>