<?php
	echo $this->menu->buildOutput();
?>
<style type="text/css">
label{
	display:inline-block;
	width:150px;
}
div#vars label{
	padding-left:150px;
}

.htmlCodeArea{
	width:600px;
	height:100px;
}
</style>
<script type="text/javascript">
$(document).ready(function(e) {
    $("input#addVar").click(function(e) {
		var count = parseInt($("input[type=hidden]#var_count").val());
        var html = '<label for="name_'+count+'">Name</label>'
		+'<input value="" name="type_vars['+count+'][name]" id="name_'+count+'" /><br />'
		+'<label for="type_'+count+'">Type</label>'
		+'<select name="type_vars['+count+'][type]" id="type_'+count+'">'
		+'	<option value="text">Textbox</option>'
		+'	<option value="WYSIWYG">WYSIWYG (CK Editor)</option>'
		+'	<option value="textarea">Textarea</option>'
		+'	<option value="upload">Upload</option>'
		+'</select><br />';
		$("div#vars").append(html);
		$("input[type=hidden]#var_count").val(count+1);
    });
});
</script>
<?php if($this->added){ ?>
	<div class="success">Your new block type has been created please review below.</div>
<?php } ?>
<?php if($this->updated){ ?>
	<div class="success">Your new block type has been changed please review below.</div>
<?php } ?>

<div class="form">
	<form action="<?php echo $this->url->getFormAddr(); ?>/id/<?php echo $this->block['type_id']; ?>" method="post" id="blockTypeFrm">
    	<div class="page">
        	<div class="title-edit">Edit Block Type</div>
            <div class="form">
            	<input type="hidden" name="posted" value="true" />
                <label for="name">Name</label>
                <input type="text" value="<?php echo $this->block['type_name']; ?>" id="name" name="name" />
                <br />
                <label for="vars">
                    Variables
                </label>
                <input type="button" id="addVar" name="add" value="Add Var" /><br />
                <div id="vars">
                    <?php $i=0; if(is_array($this->block['type_vars'])) foreach($this->block['type_vars'] as $k => $v){ ?>
                        <label for="name_<?php echo $i; ?>">Name</label>
                        <input value="<?php echo $v->name; ?>" name="type_vars[<?php echo $i; ?>][name]" id="name_<?php echo $i; ?>" /><br />
                        <label for="type_<?php echo $i; ?>">Type</label>
                        <select name="type_vars[<?php echo $i; ?>][type]" id="type_<?php echo $i; ?>">
                            <option value="text" <?php echo $v->type == "text"? "selected=\"selected\"":""; ?>>Textbox</option>
                            <option value="WYSIWYG" <?php echo $v->type == "WYSIWYG"? "selected=\"selected\"":""; ?>>WYSIWYG (CK Editor)</option>
                            <option value="textarea" <?php echo $v->type == "textarea"? "selected=\"selected\"":""; ?>>Textarea</option>
                            <option value="browse" <?php echo $v->type == "upload"? "selected=\"selected\"":""; ?>>Browse</option>
                        </select><br />
                    <?php $i++; } ?>
                </div>
                <input type="hidden" name="var_count" id="var_count" value="<?php echo $i; ?>" />
                <label for="html">HTML Code</label>	
                <textarea class="htmlCodeArea" id="html" name="html"><?php echo htmlspecialchars($this->block['type_render']); ?></textarea>
            </div>
        </div>
    </form>
</div>