<?php
	echo $this->menu->buildOutput();
?>
<style type="text/css">
ul.table li ul li.name{
	width:800px;
}
li.edit{
	width: 60px;
}
</style>
<?php if($this->removeErr){ ?>
	<div class="error">
    	There we're no blocks selected to be removed!
    </div>
<?php } ?>
<?php if($this->removed){ ?>
	<div class="success">
    	You have successfully removed the blocks from your system if they were used on a template they have been deleted!
    </div>
<?php } ?>
<form action="<?php echo $this->url->getMethodAddr("removeBlockType"); ?>" id="delTypesFrm" method="post">
<ul class="table">
	<li>
    	<ul class="header">
        	<li class="heading id">ID</li>
        	<li class="heading name">Name</li>
            <li class="heading edit">Edit</li>
            <li class="heading delete">Remove</li>
        </ul>
		<div class="clear"></div>
    </li>
<?php foreach($this->blocks as $block){ ?>
	<li>
    	<ul>
        	<li class="id">
            	<?php echo $block['type_id']; ?>
            </li>
        	<li class="name">
				<?php echo $block['type_name']; ?>
            </li>
        	<li class="edit">
            	<a href="<?php echo $this->url->getMethodAddr("editBlockType"); ?>/id/<?php echo $block['type_id']; ?>">
                	Edit
                </a>
            </li>
        	<li class="delete"><input type="checkbox" name="remove[]" value="<?php echo $block['type_id']; ?>" /></li>
        </ul>
		<div class="clear"></div>
    </li>	
<?php } ?>
</ul>
</form>
<div class="clear"></div>