<?php
	echo $this->menu->buildOutput();
?>
<style type="text/css">
.confirm{
	border:#FD410B 1px solid;
	background-color: rgba(224,41,12,0.3);
	padding:4px;
	border-radius:5px;
}
.btns{
	width: 116px;
	margin: 0 auto;
}
.btns .yes{
	width:48px;
	float: left;
}
.btns .no{
	width:48px;
	float: left;
	margin-left:20px;
}
</style>
<div class="confirm">
	<form action="<?php echo $this->url->getMethodAddr("removeBlockType"); ?>" method="post" id="remFrm">
    	<input type="hidden" name="confirm" value="true" />
	Are you sure you want to remove the following Blocks?<br />
    <?php echo $this->blocks; ?>
    </form>
	<div class="btns">
    	<div class="yes">
        	<a onclick="$('#remFrm').trigger('submit');">
        		<img src="<?php echo $this->url->getCMSImage("Tick"); ?>" alt="Confirm" title="Confirm" />
            </a>
        </div>
        <div class="no">
        	<a href="<?php echo $this->url->getMethodAddr("listBlockType"); ?>">
        		<img src="<?php echo $this->url->getCMSImage("Cross"); ?>" alt="Decline" title="Decline" />
            </a>
        </div>
        <div class="clear"></div>
    </div>
</div>