<?php
	echo $this->menu->buildOutput();
?>
<style>
ul.table li ul li.name{
	width:800px;
}
li.edit{
	width: 60px;
}
</style>
<?php if($this->removeErr){ ?>
	<div class="error">
    	There we're no blocks selected to be removed!
    </div>
<?php } ?>
<?php if($this->removed){ ?>
	<div class="success">
    	You have successfully removed the blocks from your system if they were used on a template they have been deleted!
    </div>
<?php } ?>
<form action="<?php echo $this->url->getMethodAddr("removePage"); ?>" method="post" id="delPageFrm">
<ul class="table">
	<li>
    	<ul class="header">
        	<li class="heading id">ID</li>
        	<li class="heading name">Title</li>
            <li class="heading edit">Edit</li>
            <li class="heading delete">Remove</li>
        </ul>
		<div class="clear"></div>
    </li>
<?php foreach($this->pages as $page){ ?>
	<li>
    	<ul>
        	<li class="id"><?php echo $page['page_id']; ?></li>
        	<li class="name">
				<?php echo $page['page_title']; ?>
            	<?php echo $page['homepage'] == 1? "(homepage)":""; ?>
            	<?php echo $page['e404'] == 1? "(404 page)":""; ?>
            </li>
        	<li class="edit"><a href="<?php echo $this->url->getMethodAddr("editPage"); ?>/id/<?php echo $page['page_id']; ?>">Edit</a></li>
        	<li class="delete"><input type="checkbox" name="remove[]" value="<?php echo $page['page_id']; ?>" /></li>
        </ul>
		<div class="clear"></div>
    </li>	
<?php } ?>
</ul>
<div class="clear"></div>
</form>