<?php
	echo $this->menu->buildOutput();
?>
<style>
ul.list{
	width:1020px;
}
ul.list li{
	list-style:none;
	clear:both;
}

ul.list li ul li{
	float:left;
	display:block;
	min-width:100px;
	list-style:none;
	clear:none;
}
ul.list li ul li.heading{
	font-weight:bold;
	text-align:left;
}

ul.list li ul li.title{
	width:820px;
}

ul.list li ul li.edit{
	width:60px;
}

ul.list li ul li.remove{
	width:20px;
	text-align:center;
}

</style>
<ul class="list">
	<li>
    	<ul>
        	<li class="heading title">Title</li>
            <li class="heading edit">Edit</li>
            <li class="heading remove">Remove</li>
        </ul>
    </li>
<?php foreach($this->pages as $page){ ?>
	<li>
    	<ul>
        	<li class="title">
				<?php echo $page['page_title']; ?>
            	<?php echo $page['homepage'] == 1? "(homepage)":""; ?>
            	<?php echo $page['e404'] == 1? "(404 page)":""; ?>
            </li>
        	<li class="edit"><a href="">Edit</a></li>
        	<li class="remove"><input type="checkbox" name="remove[]" value="<?php echo $page->page_id; ?>" /></li>
        </ul>
    </li>	
<?php } ?>
</ul>
<div class="clear"></div>