<?php
	echo $this->menu->buildOutput();
?>
<style>
ul.table li ul li.name{
	width:800px;
}
li.edit{
	width: 60px;
}
</style>
<ul class="table">
	<li>
    	<ul class="header">
        	<li class="heading id">ID</li>
        	<li class="heading name">Title</li>
            <li class="heading edit">Edit</li>
            <li class="heading delete">Remove</li>
        </ul>
		<div class="clear"></div>
    </li>
<?php foreach($this->pages as $page){ ?>
	<li>
    	<ul>
        	<li class="id"><?php echo $page['page_id']; ?></li>
        	<li class="name">
				<?php echo $page['page_title']; ?>
            	<?php echo $page['homepage'] == 1? "(homepage)":""; ?>
            	<?php echo $page['e404'] == 1? "(404 page)":""; ?>
            </li>
        	<li class="edit"><a href="">Edit</a></li>
        	<li class="delete"><input type="checkbox" name="remove[]" value="<?php echo $page['page_id']; ?>" /></li>
        </ul>
		<div class="clear"></div>
    </li>	
<?php } ?>
</ul>
<div class="clear"></div>